### PR TITLE
Update channel.py

### PR DESCRIPTION
**Pull request by dontbanmeplz**
Pinning messages

### CODE REVIEW

**Comment by dontbanmeplz** [comment]
Dont accept thins
Ima keep on adding to it

**Review by ZechCodes — CHANGES_REQUESTED** [review]
We should add a pin method on the message interface. This way people just need to do `await message.pin()`. It can call back to the `channel.pin` passing the message's `self.id`. I like having the option of both using just an ID or calling it on the message itself.

**Comment by dontbanmeplz** [comment]
Oh god

**Comment by ZechCodes** [comment]
Doing a complete rewrite. Closing as this no longer applies.

**Pull request closed without merging**
